### ISSUE TITLE
Android初始化失败，获取不到registerID

### ISSUE THREAD

**Issue by zcSkr** [jpush/jpush-hbuilder-plugin#1]
android甚至都不走addConnectEventListener方法回调 （小米8）
ios一切正常，可以获取到registerID

**Comment by zcSkr** [comment]
安卓包名没填对，尴尬

**Comment by jingsi1991** [comment]
> 安卓包名没填对，尴尬

请问demo的包名，安卓的有限制吗。我用的是自定义基座打包的
